### ISSUE TITLE
How can i remove process bar in flash mode?

### ISSUE THREAD

**Issue by ForeverPx** [jwplayer/jwplayer#1049]
I want to remove the process bar when the video is playing. 

How can i do ?

**Comment by ForeverPx** [comment]
@robwalch

**Comment by robwalch** [comment]
Hi @ForeverPx,

You can disable and hide all controls using `jwplayer().setControls(false);`.

If you only want to hide parts of the ui, you can do do that by adding some CSS to your page. This will hide the controlbar on all players on the page:

```css
.jwplayer .jw-controlbar {
  display: none;
}
```

You can be as specific as you want with CSS. We have classes for different player states and for each ui element. This will hide the progress bar (time-slider) only when video is playing:

```css
.jwplayer.jw-state-playing .jw-slider-time {
  display: none;
}
```

Examine the DOM for with your player in it and have a look at our CSS reference guides:

Visual develop guide
http://developer.jwplayer.com/jw-player/css-skinning-reference.html

Addition reading in the wiki
https://github.com/jwplayer/jwplayer/wiki/3.1-CSS-Skin-Classes-Reference
