### ISSUE TITLE
Subtitles' position differs when controlbar is hidden or shown

### ISSUE THREAD

**Issue by ericleroy01** [jwplayer/jwplayer#1414]
when controlbar is shown, subtitles are displayed in the middle of player.

can you set position like plyr player does ?

(http://plyr.io)

**Comment by johnBartos** [comment]
@ericleroy01 Moving the captions when the controlbar hides/shows is intentional, but they shouldn't be towards the middle of the player unless your player height is very small. Can you paste a screenshot?

**Comment by ericleroy01** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/15108986/19196492/21accc30-8cb6-11e6-8899-981ebfe6cfdb.png)

**Comment by robwalch** [comment]
Where captions appear depends on the size of the player. We're using percentages which do not work well with all player heights. @egreaves came up with "With 16 lines of captions, 1em ~= 6.25% of height".

While your screen shot looks like an issue we need to address in our CSS, we still may want two rules based on whether or not the controls are shown.

The vertical position is determined by either `.jw-captions { max-height }` when using our own renderer or `video::-webkit-media-text-track-container` when using native browser track rendering (Chrome, Edge, Safari and iOS).

You can overwrite these rules to fix captions vertically. The default settings with controls shown are:

```css
.jw-captions {
    max-height: calc(97% - 6.25 * (@controlbar-height));
}

.jwplayer video::-webkit-media-text-track-container {
    max-height: calc(97% - 6.25 * (@controlbar-height));
}
```

The controlbar is hidden when the user is inactive while the player is playing. We use these css classes on the player element to match this state `.jwplayer.jw-flag-user-inactive.jw-state-playing`. This shifts the captions down to their default position:

```css
.jwplayer.jw-flag-user-inactive.jw-state-playing .jw-captions {
    max-height: none;
}
.jwplayer.jw-flag-user-inactive.jw-state-playing video::-webkit-media-text-track-container {
    max-height: none;
}
```

If you always want the captions in the same position use max-height with more specific targets than above.
