### ISSUE TITLE
SVG icon module

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#2336]
It would be great to have a module that intelligently groups parsing of SVG assets (controlbar, sharing, etc...), lazy parses groups when getting an icon, and returns a deep clone of the parsed icon so that the SVG strings are never reparsed.

We could also benefit by doing this for templates as well.

JW8-536

**Comment by egreaves** [comment]
We should also consider the best way for publisher to replace player icons with their own.

**Comment by robwalch** [comment]
@egreaves I think that's a different issue, but my suggestion would be something like:
```css
.icon>svg {
  display: none;
}
.icon:after {
  background: url(custom-icon);
  ...
}
```
