### ISSUE TITLE
Captions styling (Safari vs Chrome)

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2979]
### Expected Behavior
One configuration for all browsers.

In the chrome and safari browser, the red text will be red.

```VTT
00:08:51.030 --> 00:08:55.230
White <c.red>Red</c>
```
```CSS
.red{
            color: red;
}
::cue(.red){
            color: green;
}
```
### Actual Behavior
In the chrome , red text is red. 
`<span class="red"> Red</span>`
Safari,  red text is green.  

https://support.jwplayer.com/articles/captions-styling-reference-for-fcc-compliance is outdated.

### Environment

- OSX 10.12.6
- Chrome 67, Safari 11.1.1
- JW 8.4.0
